### ISSUE TITLE
Cannot export image to the clipboard

### ISSUE THREAD

**Issue by a-s-russo** [jdemetra/jdplus-main#216]
When I right-click on a chart and attempt to export the image to the clipboard...

![clipboard](https://github.com/jdemetra/jdplus-main/assets/110582146/a834d70b-b868-473e-a6dd-1d5034be7876)

...an error occurs:

![error1_screenshot](https://github.com/jdemetra/jdplus-main/assets/110582146/e3f2e14c-fa87-45c4-bd73-7f9cf05031f7)

The details of the error are below:

java.lang.NullPointerException: Cannot invoke "java.util.Calendar.clone()" because "this.calendar" is null
	at java.base/java.text.DateFormat.clone(Unknown Source)
	at org.jfree.chart.axis.DateAxis.clone(DateAxis.java:1980)
	at org.jfree.util.ObjectUtilities.clone(ObjectUtilities.java:170)
	at org.jfree.chart.util.CloneUtils.cloneMapValues(CloneUtils.java:98)
	at org.jfree.chart.plot.XYPlot.clone(XYPlot.java:5538)
	at org.jfree.chart.plot.CombinedDomainXYPlot.clone(CombinedDomainXYPlot.java:776)
	at org.jfree.chart.JFreeChart.clone(JFreeChart.java:1721)
	at org.jfree.chart.ChartTransferable.<init>(ChartTransferable.java:155)
	at ec.util.chart.swing.Charts$ChartTransferable2.<init>(Charts.java:612)
	at ec.util.chart.swing.Charts.copyChart(Charts.java:429)
	at ec.util.chart.swing.JTimeSeriesChart.copyImage(JTimeSeriesChart.java:407)
	at ec.util.chart.TimeSeriesChartCommand$5.execute(TimeSeriesChartCommand.java:351)
	at ec.util.chart.swing.JTimeSeriesChartCommand$Adapter.execute(JTimeSeriesChartCommand.java:305)
	at ec.util.chart.swing.JTimeSeriesChartCommand$Adapter.execute(JTimeSeriesChartCommand.java:295)
[catch] at ec.util.various.swing.JCommand.executeSafely(JCommand.java:76)
	at ec.util.various.swing.JCommand$ActionAdapter.actionPerformed(JCommand.java:134)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at java.desktop/javax.swing.AbstractButton.doClick(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)

**Comment by a-s-russo** [comment]
Note that I can export the SI chart. After running X13 and viewing the 'Main results' for a series, it is possible to export the SI chart via the clipboard to another application, but the SA + T chart cannot be exported.

**Comment by charphi** [comment]
Thanks for submitting this issue. It has been fixed in 79ad189734ad53244594c30d66df701242faff0a.
You can already test it in the JD+ daily builds at https://github.com/nbbrd/jdemetra-app-snapshot/
