### ISSUE TITLE
Cannot open or delete a document (spec) after copying it

### ISSUE THREAD

**Issue by a-s-russo** [jdemetra/jdplus-main#228]
Consider creating a new document via **Statistical Methods** --> **Seasonal Adjustment** --> **Single Analysis** --> **X13** (for example, 'X13-Doc1'), and then dropping some data into the document.

When I then right-click on the document and select **Copy spec. to workspace**, it will appear in the Workspace panel as 'X13-Doc2' as expected. However, double-clicking on 'X13-Doc2' or right-clicking on it and selecting 'Open' either results in nothing, or an empty document panel. The error received is reported further below.

If I then attempt to delete the document by right-clicking on it and selecting 'Delete', nothing happens. (Renaming it seems to work. However, JDemetra+ then fails to shutdown when I click on the close button or **File** --> **Exit**.)

```
java.lang.NullPointerException: Cannot invoke "jdplus.toolkit.desktop.plugin.ui.processing.TsProcessingViewer.getDocument()" because "this.panel" is null
	at jdplus.toolkit.desktop.plugin.workspace.ui.WorkspaceTsTopComponent.componentClosed(WorkspaceTsTopComponent.java:106)
[catch] at org.openide.windows.WindowManager.componentCloseNotify(WindowManager.java:297)
	at org.netbeans.core.windows.WindowManagerImpl.notifyTopComponentClosed(WindowManagerImpl.java:1199)
	at org.netbeans.core.windows.Central.removeModeTopComponent(Central.java:1000)
	at org.netbeans.core.windows.Central.userClosedTopComponent(Central.java:2012)
	at org.netbeans.core.windows.view.DefaultView.userClosedTopComponent(DefaultView.java:771)
	at org.netbeans.core.windows.view.ui.TabbedHandler.actionPerformed(TabbedHandler.java:320)
	at org.netbeans.swing.tabcontrol.TabbedContainer.postActionEvent(TabbedContainer.java:711)
	at org.netbeans.swing.tabcontrol.TabbedContainerUI.shouldPerformAction(TabbedContainerUI.java:135)
	at org.netbeans.swing.tabcontrol.plaf.DefaultTabbedContainerUI.access$2700(DefaultTabbedContainerUI.java:87)
	at org.netbeans.swing.tabcontrol.plaf.DefaultTabbedContainerUI$DisplayerActionListener.actionPerformed(DefaultTabbedContainerUI.java:1263)
	at org.netbeans.swing.tabcontrol.TabDisplayer.postActionEvent(TabDisplayer.java:589)
	at org.netbeans.swing.tabcontrol.TabDisplayerUI.shouldPerformAction(TabDisplayerUI.java:168)
	at org.netbeans.swing.tabcontrol.plaf.BasicTabDisplayerUI.access$1700(BasicTabDisplayerUI.java:96)
	at org.netbeans.swing.tabcontrol.plaf.BasicTabDisplayerUI$BasicDisplayerMouseListener.performCommand(BasicTabDisplayerUI.java:761)
	at org.netbeans.swing.tabcontrol.plaf.BasicTabDisplayerUI$BasicDisplayerMouseListener.potentialCommand(BasicTabDisplayerUI.java:746)
	at org.netbeans.swing.tabcontrol.plaf.BasicTabDisplayerUI$BasicDisplayerMouseListener.mouseReleased(BasicTabDisplayerUI.java:795)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(Unknown Source)
	at java.desktop/java.awt.Component.processMouseEvent(Unknown Source)
	at java.desktop/javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.Component.processEvent(Unknown Source)
	at java.desktop/java.awt.Container.processEvent(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.Component.dispatchEvent(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$4.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.desktop/java.awt.EventQueue$5.run(Unknown Source)
	at java.base/java.security.AccessController.doPrivileged(Unknown Source)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.desktop/java.awt.EventQueue.dispatchEvent(Unknown Source)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.desktop/java.awt.EventDispatchThread.run(Unknown Source)
```

**Comment by charphi** [comment]
Here is a screenshot for reference:

![2024-05-28 11_50_42-Window](https://github.com/jdemetra/jdplus-main/assets/8778378/61067f1c-3a89-4522-bf17-ac2e92d29f25)

**Comment by a-s-russo** [comment]
Hi @Immurb. Thanks for attending to this ticket. I've attempted to verify this fix using the 3.2.3 snapshot you refer to above, but I'm not sure the fix is working as intended. In version 3.2.2 with the bug present, I could copy a spec and have it appear, but then it would not open/delete etc. as explained above:

![image](https://github.com/jdemetra/jdplus-main/assets/110582146/43d74812-cd03-4b9f-b907-b107647122c6)

However, with version 3.2.3 that supposedly incorporates the bug fix, when I click on 'Copy spec. to workspace', nothing happens (that is, I do not see a 'X13Doc-2' document in the list):

![image](https://github.com/jdemetra/jdplus-main/assets/110582146/291169c8-40aa-4be8-888a-9a41e12a041d)

Is this the intended behaviour, or has the fixed not been implemented correctly?

The daily snapshot version I used to test the bug fix is below. Please let me know if this was the incorrect version to have used.

![image](https://github.com/jdemetra/jdplus-main/assets/110582146/df6fa395-385f-4aaf-ba52-2320ea60a70b)

**Comment by Immurb** [comment]
The bug existed because the action created a document, in your case X13Doc-2, but internally it was a specification item. Now it creates a specification as the text suggests.
The copied specification should be created under "specifications" instead of "documents" as was the case in version 2.

**Comment by a-s-russo** [comment]
Hi @Immurb. Thanks for your prompt reply, and sorry for my delayed response. I understand now how the copying spec functionality is supposed to work. I have tested it and indeed it works as intended.
