### ISSUE TITLE
Fix NPE when calling contextual menu on variable window

### ISSUE THREAD

**Issue by charphi** [jdemetra/jdplus-main#275]
```
SEVERE [global]
java.lang.NullPointerException: Cannot invoke "String.endsWith(String)" because "path" is null
	at org.openide.util.lookup.Lookups.forPath(Lookups.java:206)
	at org.openide.util.Utilities.actionsForPath(Utilities.java:1953)
	at jdplus.toolkit.desktop.plugin.ui.Menus.createActions(Menus.java:39)
	at jdplus.toolkit.desktop.plugin.ui.Menus.fillMenu(Menus.java:68)
	at jdplus.toolkit.desktop.plugin.ui.Menus.fillMenu(Menus.java:64)
	at jdplus.toolkit.desktop.plugin.workspace.ui.WorkspaceTopComponent.fill(WorkspaceTopComponent.java:65)
	at jdplus.toolkit.desktop.plugin.ui.ActiveViewManager$1.menuSelected(ActiveViewManager.java:98)
```

![image](https://github.com/jdemetra/jdplus-main/assets/8778378/ab822643-8497-4a95-8626-41361d5c2235)

**Comment by charphi** [comment]
Cannot reproduce the problem !?
