### ISSUE TITLE
Cannot handle family: Utilities@Calendars

### ISSUE THREAD

**Issue by ashah12** [jdemetra/jdplus-main#284]
When running **_locally,_** there do not seem to be any issues with the application. 

However, when trying to run this in an **_AWS Lambda function_**, 
I get the java.io.IOException: Cannot handle family: Utilities@Calendars

Would you happen to know what part of the application causes this/the reason behind such an error?

![Error log](https://github.com/jdemetra/jdplus-main/assets/30942365/07ca876f-8508-45b4-9a93-d1899c6bdb30)

**Details of the error:**
May 08, 2024 12:58:25 AM jdplus.cruncher.App reportException
SEVERE: null
java.io.IOException: Cannot handle family: Utilities@Calendars
at internal.toolkit.base.workspace.file.SafeHandler.get(SafeHandler.java:49)
at internal.toolkit.base.workspace.file.SafeHandler.loadValue(SafeHandler.java:59)
at internal.toolkit.base.workspace.file.FileWorkspaceImpl.load(FileWorkspaceImpl.java:133)
at jdplus.toolkit.base.workspace.WorkspaceUtility.loadAllCalendars(WorkspaceUtility.java:72)
at jdplus.toolkit.base.workspace.WorkspaceUtility.context(WorkspaceUtility.java:62)
at jdplus.cruncher.App.process(App.java:109)
at jdplus.cruncher.App.main(App.java:73)
at au.gov.abs.sats.CruncherLambdaHandler.handleRequest(CruncherLambdaHandler.java:48)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.base/java.lang.reflect.Method.invoke(Unknown Source)
at com.amazonaws.services.lambda.runtime.api.client.EventHandlerLoader$PojoMethodRequestHandler.handleRequest(EventHandlerLoader.java:285)
at com.amazonaws.services.lambda.runtime.api.client.EventHandlerLoader$PojoHandlerAsStreamHandler.handleRequest(EventHandlerLoader.java:202)
at com.amazonaws.services.lambda.runtime.api.client.EventHandlerLoader$2.call(EventHandlerLoader.java:905)
at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.startRuntime(AWSLambda.java:245)
at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.startRuntime(AWSLambda.java:197)
at com.amazonaws.services.lambda.runtime.api.client.AWSLambda.main(AWSLambda.java:187)
IOException: Cannot handle family: Utilities@Calendars

**Comment by charphi** [comment]
Hi @ashah12 

JWsaCruncher is a command-line tool. It is not designed to run as a AWS lambda function.
It might still work but you will have to create some kind of wrapper around it (maybe it is what you are already doing).

Concerning your specific error, the message means that JD+ has not been able to load the service provider that deals with `Utilities@Calendars` workspace item. I'm not familiar with AWS lambda function, so I'm not sure where the problem is.
It might come from a missing jar or a missing entry in the jar if the content has been modified or repackaged.

Service providers are loaded by the [Java ServiceLoader](https://www.baeldung.com/java-spi). On the classpath, these providers are registered in `META-INF/services` folders. On module path, these providers are registered in `module-info.java`.

**Comment by ashah12** [comment]
Thank you for your help!

**Comment by bezdomniy** [comment]
Hi,
I'm trying to figure our where the service provider configuration files are defined. There don't seem to be any META-INF directory in the jdplus-main repo. 

I am trying to create an executable jar, which includes the jdplus dependencies. However when I do this, the only service providers that the jar sees are:
jdplus.sa.base.workspace.SaHandlers$SaMulti@49e4cb85
jdplus.sa.base.workspace.SaHandlers$SaMultiLegacy@5594a1b5

any ideas?

**Comment by charphi** [comment]
@bezdomniy Service provider configuration files are automatically generated at compile time thanks to nice annotations (see [`@ServiceProvider`](https://github.com/nbbrd/java-service-util?tab=readme-ov-file#serviceprovider)).

For your executable jar, you might need to shade your dependencies using the [`maven-shade-plugin`](https://maven.apache.org/plugins/maven-shade-plugin/). You will have to use a transformer in order to shade the providers.
https://github.com/jdemetra/jdplus-main/blob/ddf9ce62f5f89bdd957cac10f03017e01db141f8/jdplus-main-cli/pom.xml#L73

**Comment by ashah12** [comment]
This was the solution for the Calendars issue as well! 😊
