### ISSUE TITLE
Fix grid parsing when some headers are null

### ISSUE THREAD

**Issue by charphi** [jdemetra/jdplus-main#328]
IDE log:
```
java.lang.IndexOutOfBoundsException: Index 48 out of bounds for length 48
               at java.base/jdk.internal.util.Preconditions.outOfBounds(Unknown Source)
               at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Unknown Source)
               at java.base/jdk.internal.util.Preconditions.checkIndex(Unknown Source)
               at java.base/java.util.Objects.checkIndex(Unknown Source)
               at java.base/java.util.ArrayList.get(Unknown Source)
               at jdplus.toolkit.base.tsp.grid.GridReader.readPeriodByRow(GridReader.java:223)
               at jdplus.toolkit.base.tsp.grid.GridReader.read(GridReader.java:94)
               at internal.spreadsheet.base.api.grid.SheetGrid.readSheet(SheetGrid.java:111)
               at internal.spreadsheet.base.api.grid.SheetGrid.getSheetByName(SheetGrid.java:80)
               at internal.spreadsheet.base.api.grid.SheetGrid.getSheetByName(SheetGrid.java:55)
               at internal.spreadsheet.base.api.CachedSpreadSheetConnection.getSheetByName(CachedSpreadSheetConnection.java:60)
               at internal.spreadsheet.base.api.SpreadSheetSupport$PooledSpreadSheetConnection.getSheetByName(SpreadSheetSupport.java:224)
               at internal.spreadsheet.base.api.SpreadSheetSupport.getData(SpreadSheetSupport.java:124)
               at jdplus.toolkit.base.tsp.stream.TsStreamAsProvider.fill(TsStreamAsProvider.java:146)
               at jdplus.toolkit.base.tsp.stream.TsStreamAsProvider.getTs(TsStreamAsProvider.java:104)
               at jdplus.spreadsheet.base.api.SpreadSheetProvider.getTs(SpreadSheetProvider.java:67)
```

**Comment by charphi** [comment]
Sample:
```java
    public final ArrayGridInput VGRID_GAP1 = ArrayGridInput.of(new Object[][]{
            {null, null, "S1", null},
            {JAN_, null, 3.14, null},
            {FEB_, null, 4.56, null},
            {MAR_, null, 7.89, null},
            {null, null, null, null}
    });

    public final ArrayGridInput VGRID_GAP2 = ArrayGridInput.of(new Object[][]{
            {null, null, null, null},
            {null, null, "S1", null},
            {JAN_, null, 3.14, null},
            {FEB_, null, 4.56, null},
            {MAR_, null, 7.89, null},
            {null, null, null, null}
    });

    public final ArrayGridInput VGRID_GAP3 = ArrayGridInput.of(new Object[][]{
            {null, null, "G1", null},
            {null, null, "S1", null},
            {JAN_, null, 3.14, null},
            {FEB_, null, 4.56, null},
            {MAR_, null, 7.89, null},
            {null, null, null, null}
    });
```
