### ISSUE TITLE
Unable to refresh multi-document SA

### ISSUE THREAD

**Issue by walkman-w902** [jdemetra/jdplus-main#482]
I'm trying to update data from Excel file in multi-document SA with custom made specification for each time series, but whether I select "Refresh" from document header or through right-click menu for one series with any revision option their status becomes "Invalid" and quality "Undefined". Refresh from the same file in single document SA works fine, so I think it's not the issue with file or path. Program event viewer says "unexpected exception" with the following detail:

`java.lang.IllegalStateException
	at jdplus.toolkit.base.api.timeseries.TsDomain.checkNonEmpty(TsDomain.java:347)
	at jdplus.toolkit.base.api.timeseries.TsDomain.getEndPeriod(TsDomain.java:93)
	at jdplus.toolkit.base.api.timeseries.TsData.getEnd(TsData.java:140)
	at jdplus.sa.base.api.SaItem.refresh(SaItem.java:295)
	at jdplus.sa.desktop.plugin.multiprocessing.ui.MultiProcessingDocument.refresh(MultiProcessingDocument.java:175)
	at jdplus.sa.desktop.plugin.multiprocessing.ui.SaBatchUI.refresh(SaBatchUI.java:480)
	at jdplus.sa.desktop.plugin.multiprocessing.ui.SaBatchUI.refresh(SaBatchUI.java:465)
	at jdplus.sa.desktop.plugin.multiprocessing.actions.LocalRefreshCurrent.process(LocalRefreshCurrent.java:37)
	at jdplus.sa.desktop.plugin.multiprocessing.actions.LocalRefreshCurrent.process(LocalRefreshCurrent.java:18)
	at jdplus.toolkit.desktop.plugin.ui.ActiveViewAction.actionPerformed(ActiveViewAction.java:42)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1972)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2314)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:407)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:374)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1029)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1073)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6621)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3398)
	at java.desktop/java.awt.Component.processEvent(Component.java:6386)
	at java.desktop/java.awt.Container.processEvent(Container.java:2266)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:4996)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2324)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4948)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4575)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4516)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2310)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2780)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4828)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:775)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:720)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:714)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:98)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:747)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:400)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:87)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:744)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
[catch] at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
`

**Comment by walkman-w902** [comment]
I'm sorry, it seems to be my fault. I've tried to update SA on machine that seems to have corrupted JDK installation - after I performed clear installation of the kit Jdemetra updates multi-SA documents fine.

The issue can be closed now.
